### ISSUE TITLE
Promoting the Event

### ISSUE THREAD

**Issue by allella** [OpenUpstate/OpenDataDay2015#2]

**Comment by allella** [comment]
@BigBlueHat Who's been reached out to?  Has Code for Greenville announced it? Seems like the type of folks who would be interested.

**Comment by BigBlueHat** [comment]
@allella yeah, I wrote @wryenmeek a couple weeks back, he CC'd @leadkrabi who just responded late last night that he can't make it. :frowning: 

So...if you know of other Code for Greenville folks, please invite them! :smile:

**Comment by BigBlueHat** [comment]
@OpenUpstate/greenville curious how many of you knew / found-out that Open Data Day was happening again in Greenville, SC this year?
http://attending.io/events/open-upstate-data-day

Anyone? :smiley:

**Comment by jeremywight** [comment]
yeah sorry about that guys. I hadn't heard about it until the message that I was included on and already had plans.

**Comment by BigBlueHat** [comment]
@jeremywight we have a newsletter now!...as of...last week. :stuck_out_tongue: 
http://openupstate.org/ (top left corner). :wink:

Hope to have you here next time!
